language: python
sudo: true

before_install:
  - sudo apt-get -y install pandoc

before_script: 
  - pandoc --version
  - alias pandoc='pandoc --data-dir=/home/travis/.pandoc'

install:
  - pip install tox
script:
  - tox -r
matrix:
    include:

        - python: 3.7
          env: TOXENV=docs
          dist: xenial
          sudo: true

after_success:
  bash <(curl -s https://codecov.io/bash)