language: python
sudo: true

addons:
  apt:
    packages:
      - pandoc

install:
  - pip install tox
script:
  - tox -r
matrix:
    include:

        - python: 3.7
          env: TOXENV=docs
          dist: xenial
          sudo: true

after_success:
  bash <(curl -s https://codecov.io/bash)